replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-spring-jkube-jenkins-eve/hello@sha256:65df97f72a0059c1db30460b0cd5650447c48d2162179cca2e4cb7d443435069 # written by ploigos-step-runner
